// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProfileService.Data;

#nullable disable

namespace ProfileService.Data.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    partial class ProfileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProfileService.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsoCode = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            IsoCode = "AX",
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Id = 3,
                            IsoCode = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 4,
                            IsoCode = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 5,
                            IsoCode = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 6,
                            IsoCode = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 7,
                            IsoCode = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 8,
                            IsoCode = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 9,
                            IsoCode = "AG",
                            Name = "Antigua & Barbuda"
                        },
                        new
                        {
                            Id = 10,
                            IsoCode = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 11,
                            IsoCode = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 12,
                            IsoCode = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 13,
                            IsoCode = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 14,
                            IsoCode = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 15,
                            IsoCode = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 16,
                            IsoCode = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 17,
                            IsoCode = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 18,
                            IsoCode = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 19,
                            IsoCode = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 20,
                            IsoCode = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 21,
                            IsoCode = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 22,
                            IsoCode = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 23,
                            IsoCode = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 24,
                            IsoCode = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 25,
                            IsoCode = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 26,
                            IsoCode = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 27,
                            IsoCode = "BQ",
                            Name = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            Id = 28,
                            IsoCode = "BA",
                            Name = "Bosnia & Herzegovina"
                        },
                        new
                        {
                            Id = 29,
                            IsoCode = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 30,
                            IsoCode = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 31,
                            IsoCode = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 32,
                            IsoCode = "VG",
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Id = 33,
                            IsoCode = "BN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 34,
                            IsoCode = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 35,
                            IsoCode = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 36,
                            IsoCode = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 37,
                            IsoCode = "CV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 38,
                            IsoCode = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 39,
                            IsoCode = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 40,
                            IsoCode = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 41,
                            IsoCode = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 42,
                            IsoCode = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 43,
                            IsoCode = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 44,
                            IsoCode = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 45,
                            IsoCode = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 46,
                            IsoCode = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = 47,
                            IsoCode = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 48,
                            IsoCode = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 49,
                            IsoCode = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 50,
                            IsoCode = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 51,
                            IsoCode = "CD",
                            Name = "Congo (DRC)"
                        },
                        new
                        {
                            Id = 52,
                            IsoCode = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 53,
                            IsoCode = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 54,
                            IsoCode = "CI",
                            Name = "Côte d’Ivoire"
                        },
                        new
                        {
                            Id = 55,
                            IsoCode = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 56,
                            IsoCode = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 57,
                            IsoCode = "CW",
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = 58,
                            IsoCode = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 59,
                            IsoCode = "CZ",
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = 60,
                            IsoCode = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 61,
                            IsoCode = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 62,
                            IsoCode = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 63,
                            IsoCode = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 64,
                            IsoCode = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 65,
                            IsoCode = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 66,
                            IsoCode = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 67,
                            IsoCode = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 68,
                            IsoCode = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 69,
                            IsoCode = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 70,
                            IsoCode = "SZ",
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 71,
                            IsoCode = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 72,
                            IsoCode = "FK",
                            Name = "Falkland Islands"
                        },
                        new
                        {
                            Id = 73,
                            IsoCode = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 74,
                            IsoCode = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 75,
                            IsoCode = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 76,
                            IsoCode = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = 77,
                            IsoCode = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 78,
                            IsoCode = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 79,
                            IsoCode = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 80,
                            IsoCode = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 81,
                            IsoCode = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 82,
                            IsoCode = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 83,
                            IsoCode = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 84,
                            IsoCode = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 85,
                            IsoCode = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 86,
                            IsoCode = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 87,
                            IsoCode = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 88,
                            IsoCode = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 89,
                            IsoCode = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 90,
                            IsoCode = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 91,
                            IsoCode = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = 92,
                            IsoCode = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 93,
                            IsoCode = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 94,
                            IsoCode = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 95,
                            IsoCode = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 96,
                            IsoCode = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 97,
                            IsoCode = "HK",
                            Name = "Hong Kong SAR"
                        },
                        new
                        {
                            Id = 98,
                            IsoCode = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 99,
                            IsoCode = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 100,
                            IsoCode = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 101,
                            IsoCode = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 102,
                            IsoCode = "IR",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 103,
                            IsoCode = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 104,
                            IsoCode = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 105,
                            IsoCode = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = 106,
                            IsoCode = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 107,
                            IsoCode = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 108,
                            IsoCode = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 109,
                            IsoCode = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 110,
                            IsoCode = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 111,
                            IsoCode = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 112,
                            IsoCode = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 113,
                            IsoCode = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 114,
                            IsoCode = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 115,
                            IsoCode = "KR",
                            Name = "Korea"
                        },
                        new
                        {
                            Id = 116,
                            IsoCode = "XK",
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = 117,
                            IsoCode = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 118,
                            IsoCode = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 119,
                            IsoCode = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 120,
                            IsoCode = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 121,
                            IsoCode = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 122,
                            IsoCode = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 123,
                            IsoCode = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 124,
                            IsoCode = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 125,
                            IsoCode = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 126,
                            IsoCode = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 127,
                            IsoCode = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 128,
                            IsoCode = "MO",
                            Name = "Macao SAR"
                        },
                        new
                        {
                            Id = 129,
                            IsoCode = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 130,
                            IsoCode = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 131,
                            IsoCode = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 132,
                            IsoCode = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 133,
                            IsoCode = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 134,
                            IsoCode = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 135,
                            IsoCode = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 136,
                            IsoCode = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 137,
                            IsoCode = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 138,
                            IsoCode = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 139,
                            IsoCode = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 140,
                            IsoCode = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 141,
                            IsoCode = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 142,
                            IsoCode = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 143,
                            IsoCode = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 144,
                            IsoCode = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 145,
                            IsoCode = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 146,
                            IsoCode = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 147,
                            IsoCode = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 148,
                            IsoCode = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 149,
                            IsoCode = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 150,
                            IsoCode = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 151,
                            IsoCode = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 152,
                            IsoCode = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 153,
                            IsoCode = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 154,
                            IsoCode = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 155,
                            IsoCode = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 156,
                            IsoCode = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 157,
                            IsoCode = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 158,
                            IsoCode = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 159,
                            IsoCode = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 160,
                            IsoCode = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = 161,
                            IsoCode = "KP",
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 162,
                            IsoCode = "MK",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 163,
                            IsoCode = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 164,
                            IsoCode = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 165,
                            IsoCode = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 166,
                            IsoCode = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 167,
                            IsoCode = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 168,
                            IsoCode = "PS",
                            Name = "Palestinian Authority"
                        },
                        new
                        {
                            Id = 169,
                            IsoCode = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 170,
                            IsoCode = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 171,
                            IsoCode = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 172,
                            IsoCode = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 173,
                            IsoCode = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 174,
                            IsoCode = "PN",
                            Name = "Pitcairn Islands"
                        },
                        new
                        {
                            Id = 175,
                            IsoCode = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 176,
                            IsoCode = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 177,
                            IsoCode = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 178,
                            IsoCode = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 179,
                            IsoCode = "RE",
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = 180,
                            IsoCode = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 181,
                            IsoCode = "RU",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 182,
                            IsoCode = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 183,
                            IsoCode = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 184,
                            IsoCode = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 185,
                            IsoCode = "ST",
                            Name = "São Tomé & Príncipe"
                        },
                        new
                        {
                            Id = 186,
                            IsoCode = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 187,
                            IsoCode = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 188,
                            IsoCode = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 189,
                            IsoCode = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 190,
                            IsoCode = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 191,
                            IsoCode = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 192,
                            IsoCode = "SX",
                            Name = "Sint Maarten"
                        },
                        new
                        {
                            Id = 193,
                            IsoCode = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 194,
                            IsoCode = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 195,
                            IsoCode = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 196,
                            IsoCode = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 197,
                            IsoCode = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 198,
                            IsoCode = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 199,
                            IsoCode = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 200,
                            IsoCode = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 201,
                            IsoCode = "SH",
                            Name = "St Helena, Ascension, Tristan da Cunha"
                        },
                        new
                        {
                            Id = 202,
                            IsoCode = "BL",
                            Name = "St. Barthélemy"
                        },
                        new
                        {
                            Id = 203,
                            IsoCode = "KN",
                            Name = "St. Kitts & Nevis"
                        },
                        new
                        {
                            Id = 204,
                            IsoCode = "LC",
                            Name = "St. Lucia"
                        },
                        new
                        {
                            Id = 205,
                            IsoCode = "MF",
                            Name = "St. Martin"
                        },
                        new
                        {
                            Id = 206,
                            IsoCode = "PM",
                            Name = "St. Pierre & Miquelon"
                        },
                        new
                        {
                            Id = 207,
                            IsoCode = "VC",
                            Name = "St. Vincent & Grenadines"
                        },
                        new
                        {
                            Id = 208,
                            IsoCode = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 209,
                            IsoCode = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 210,
                            IsoCode = "SJ",
                            Name = "Svalbard & Jan Mayen"
                        },
                        new
                        {
                            Id = 211,
                            IsoCode = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 212,
                            IsoCode = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 213,
                            IsoCode = "SY",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 214,
                            IsoCode = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 215,
                            IsoCode = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 216,
                            IsoCode = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 217,
                            IsoCode = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 218,
                            IsoCode = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 219,
                            IsoCode = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 220,
                            IsoCode = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 221,
                            IsoCode = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 222,
                            IsoCode = "TT",
                            Name = "Trinidad & Tobago"
                        },
                        new
                        {
                            Id = 223,
                            IsoCode = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 224,
                            IsoCode = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 225,
                            IsoCode = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 226,
                            IsoCode = "TC",
                            Name = "Turks & Caicos Islands"
                        },
                        new
                        {
                            Id = 227,
                            IsoCode = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 228,
                            IsoCode = "UM",
                            Name = "U.S. Outlying Islands"
                        },
                        new
                        {
                            Id = 229,
                            IsoCode = "VI",
                            Name = "U.S. Virgin Islands"
                        },
                        new
                        {
                            Id = 230,
                            IsoCode = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 231,
                            IsoCode = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 232,
                            IsoCode = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 233,
                            IsoCode = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 234,
                            IsoCode = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 235,
                            IsoCode = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 236,
                            IsoCode = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 237,
                            IsoCode = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 238,
                            IsoCode = "VA",
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 239,
                            IsoCode = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 240,
                            IsoCode = "VN",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 241,
                            IsoCode = "WF",
                            Name = "Wallis & Futuna"
                        },
                        new
                        {
                            Id = 242,
                            IsoCode = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 243,
                            IsoCode = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 244,
                            IsoCode = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("ProfileService.Entities.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Interests")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("References")
                        .IsRequired()
                        .HasColumnType("varchar(80)[]");

                    b.HasKey("UserId")
                        .HasName("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ProfileService.Entities.Profile", b =>
                {
                    b.HasOne("ProfileService.Entities.Country", "Country")
                        .WithMany("Profiles")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ProfileService.Entities.Country", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
