version: "3.9"

services:
  gateway:
    build:
      context: ../.
      dockerfile: ./src/GatewayService/Dockerfile
    image: gateway-service
    container_name: gateway
  identity-api:
    build:        
      context: ../.
      dockerfile: ./src/IdentityService/Dockerfile
    image: identity-service
    container_name: identity-api
    ports:
      - "8081:8080"
    volumes:
      - users_secrets:/root/.microsoft/UserSecrets/${USER_SECRETS_ID}:ro
    depends_on:
      - users-postgres
  users-postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    volumes:
      - users_data:/var/users/data

volumes:
  users_data:
  users_secrets:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${APPDATA}/Microsoft/UserSecrets/${USER_SECRETS_ID}
  
    