version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  smp-postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  gateway-service:
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Docker
      - JWT__SecretKey=${JWT_SECRET_KEY}
      - JWT__ExpiryDays=${JWT_EXPIRY_DAYS}
    build:
      context: ../.
      dockerfile: ./src/GatewayService/Dockerfile
    image: gateway-service
    ports:
      - "5098:80"
    container_name: gateway
  identity-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - JWT__SecretKey=${JWT_SECRET_KEY}
      - JWT__ExpiryDays=${JWT_EXPIRY_DAYS}
      - ConnectionStrings__PostgresConnection=Server=smp-postgres:5432;User Id=postgres;Password=password;Database=users
    build:
      context: ../.
      dockerfile: ./src/IdentityService/Dockerfile
    image: identity-service
    container_name: identity-service
    ports:
      - "5171:80"
    depends_on:
      - smp-postgres
      - rabbitmq
  profile-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - JWT__SecretKey=${JWT_SECRET_KEY}
      - JWT__ExpiryDays=${JWT_EXPIRY_DAYS}
      - AWS__AccessKey=${AWS_ACCESS_KEY_ID}
      - AWS__SecretKey=${AWS_SECRET_ACCESS_KEY}
      - ConnectionStrings__PostgresConnection=Server=smp-postgres:5432;User Id=postgres;Password=password;Database=profiles
    build:
      context: ../.
      dockerfile: ./src/ProfileService/Dockerfile
    image: profile-service
    container_name: profile-service
    ports:
      - "5172:80"
    depends_on:
      - rabbitmq
      - smp-postgres
  stories-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - JWT__SecretKey=${JWT_SECRET_KEY}
      - JWT__ExpiryDays=${JWT_EXPIRY_DAYS}
      - ConnectionStrings__PostgresConnection=Server=smp-postgres:5432;User Id=postgres;Password=password;Database=stories
    build:
      context: ../.
      dockerfile: ./src/StoriesService/Dockerfile
    image: stories-service
    container_name: stories-service
    ports:
      - "5173:80"
    depends_on:
      - smp-postgres


volumes:
  postgres_data: