version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  smp-postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  gateway-service:
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: ../.
      dockerfile: ./src/GatewayService/Dockerfile
    image: gateway-service
    ports:
      - "5098:80"
    container_name: gateway
  identity-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "RabbitMq__Host=rabbitmq"
      - "ConnectionStrings:PostgresConnection=Server=smp-postgres:5432;User Id=postgres;Password=password;Database=users"
    build:
      context: ../.
      dockerfile: ./src/IdentityService/Dockerfile
    image: identity-service
    container_name: identity-service
    ports:
      - "5171:80"
    volumes:
      - $APPDATA\Microsoft\UserSecrets:/root/.microsoft/UserSecrets:ro
    depends_on:
      - smp-postgres
      - rabbitmq
  profile-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "RabbitMq__Host=rabbitmq"
      - "ConnectionStrings:PostgresConnection=Server=smp-postgres:5432;User Id=postgres;Password=password;Database=profiles"
    build:
      context: ../.
      dockerfile: ./src/ProfileService/Dockerfile
    image: profile-service
    container_name: profile-service
    ports:
      - "5172:80"
    depends_on:
      - rabbitmq
      - smp-postgres

volumes:
  postgres_data:
    