POST http://localhost:5171/accounts/register
Content-Type : application/json 

{
    "firstname" : "Vadim",
    "lastname" : "Budchanin",
    "email" : "vbudchanin@list.ru",
    "password" : "PasswordTest123",
    "confirmPassword" : "PasswordTest123"
}