@GatewayService_HostAddress = http://localhost:5098

POST {{GatewayService_HostAddress}}/user/register
Content-Type: application/json

{
  "firstname": "vadim",
  "lastname": "budchanin",
  "username": "rewrrt",
  "email": "v@tew.com",
  "password": "vadim12345",
  "confirmpassword": "vadim12345"
}

