#name: CD
#
#on:
#  workflow_run:
#    workflows: ["CI"]
#    types: ["completed"]
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Deploy to AWS
#        uses: andrewdex/s3-deploy-action@v1.0.6
#        with:
#          #TODO: Write Credentials